//locale
export const LOAD_LOCALE_SUCCESS = 'LOAD_LOCALE_SUCCESS'
export const CHANGE_LOCALE_SUCCESS = 'CHANGE_LOCALE_SUCCESS'
//auth
export const SAVE_AUTH_SUCCESS = 'SAVE_AUTH_SUCCESS'
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS'
//Profile
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
